spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  data:
    rest:
      base-path: /api
server:
  port: 8585
logging:
  file:
    name: TacoCloud.log
  level:
    root: WARN
    org.springframework.security: DEBUG
    com.mechague.tacocloud: DEBUG
greeting:
  welcome: You are using ${spring.application.name}
taco:
  orders:
    pageSize: 10

#---
#spring:
#  profiles: prod
#  datasource:
#   url: jdbc:mysql://localhost/tacocloud
#   username: tacouser
#   password: tacopassword
#   logging:
# level:
#   com.mechague.tacocloud: DEBUG