package com.mechague.tacocloud.domain;

import lombok.Data;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.rest.core.annotation.RestResource;
import org.springframework.hateoas.RepresentationModel;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.Date;
import java.util.List;

@Entity
//Lombook annotation  @see <a href="https://projectlombok.org">Project Lombook</a>
@Data
//Define the path and the name in the response body generated by Spring Data REST
@RestResource(path = "tacos", rel = "tacos")
public class Taco extends RepresentationModel<Taco> {
    //The library of those validation annotations already comes with the dependency spring boot starter
    @NotNull
    @Size(min=5, message="Name must be at least 5 characters long")
    private String name;

    @NotNull(message = "You must choose at least 1 ingredient")
    @Size(min=1, message="You must choose at least 1 ingredient")
    @ManyToMany(targetEntity = Ingredient.class)
    private List<Ingredient> ingredients;

    //Chapter 3
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @CreatedDate
    private Date createdAt;

    @PrePersist
    void createdAt() {
        this.createdAt = new Date();
    }

}
